services:
  - type: web
    name: dheeran-restaurant
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OSRM_BASE_URL
        value: http://router.project-osrm.org
      - key: NTFY_SERVER_URL
        value: https://ntfy.sh
      - key: NTFY_TOPIC
        value: restaurant-orders-8f72x91k
